services:
  mysql:
    image: mysql:8.0
    container_name: testtable-local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: testproject
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
    ports:
      - "3307:3306"
    volumes:
      - test:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  test:
